### ISSUE TITLE
Ergaenzung Vorletzte Seite

### ISSUE THREAD

**Issue by munnich** [benjaminbutton13659/Latex-Mitschriebe-Semester-3#6]
`I_T=I_0\frac{1}{1+F\sin^2\left(\frac{\Delta\vphi}{2}\right)}
F=\frac{4R}{(1-R)^2}\ \ \frac{\Delta\vphi}{2}=2\pi\frac{d}{\lambda}\sqrt{n^2-\sin^2\alpha}
`
Das sollten die fehlenden Formeln sein.

**Comment by benjaminbutton13659** [comment]
Danke ist Eingefügt.
